version: "3.1"
services:
    rabbit:
      image: rabbitmq:3.7.5-alpine
      ports:
        - "5672:5672"
        - "15672:15672"
    app:
      build: ./docker
      links:
        - rabbit:rabbit
      entrypoint:
        - /home/user/dev-entrypoint.sh
